"""SurfactantKit: surfactant and interfacial-science theory as a tested,
importable library.

Implements Clint ideal mixing, Rubingh/Rosen regular-solution theory,
the Gibbs adsorption isotherm, HLB, the critical packing parameter,
electrostatics (Debye length, zeta potential), dynamics (hydrodynamic
radius), and full micellization thermodynamics -- the calculations an
AI assistant or a researcher needs to reason correctly about surfactant
systems instead of hallucinating numbers.
"""

from .mixed_micelle import (
    clint_ideal_cmc,
    solve_rubingh_x,
    rubingh_beta,
    rubingh_beta_regression,
    activity_coefficients,
    asymmetric_margules_activity_coefficients,
    eommm_global_fit,
    excess_free_energy,
    solve_rosen_monolayer_x,
    rosen_beta_sigma,
    corrin_harkins_predict_cmc,
    motomura_ideal_composition,
    rodenas_x1,
    rodenas_x1_series,
    rodenas_activity_coefficients,
    maeda_free_energy_of_micellization,
)
from .adsorption import (
    gibbs_gamma_max,
    gibbs_a_min,
    szyszkowski_surface_tension,
    szyszkowski_fit_K,
    frumkin_theta,
    frumkin_surface_tension,
)
from .hlb import (
    hlb_griffin,
    hlb_davies,
    guo_effective_eo_chain_length,
    guo_effective_alkyl_chain_length,
    guo_effective_po_chain_length,
    hlb_davies_guo_ecl,
)
from .hld import (
    hld_ionic,
    hld_nonionic,
    cc_mixing_rule,
    optimal_salinity_ionic,
    hlb_from_cc_cationic_quat,
    fit_k_and_cc_from_salinity_scan,
)
from .cpp import (
    tanford_tail_volume,
    tanford_critical_length,
    critical_packing_parameter,
    classify_aggregate_morphology,
    aggregation_number_spherical,
    nagarajan_debye_huckel_kappa_inverse,
    nagarajan_equilibrium_area_ionic,
)
from .electrostatics import (
    ionic_strength,
    debye_length,
    henry_function,
    zeta_potential_henry,
    electrophoretic_mobility_relaxation_corrected,
    zeta_potential_relaxation_corrected,
    grahame_equation_surface_potential,
)
from .dynamics import (
    hydrodynamic_radius_stokes_einstein,
    perrin_friction_factor,
    hydrodynamic_radius_perrin_corrected,
)
from .thermodynamics import (
    cmc_to_mole_fraction,
    counterion_binding_degree,
    gibbs_free_energy_micellization,
    mass_action_free_energy_of_micellization,
    vant_hoff_enthalpy,
    vant_hoff_multi_point_fit,
    entropy_micellization,
)
from .wetting import (
    work_of_adhesion,
    spreading_coefficient,
    capillary_number,
    owens_wendt_solid_surface_energy,
    van_oss_chaudhury_good_solid_surface_energy,
)
from .solubilization import molar_solubilization_ratio, micelle_water_partition_coefficient
from .curve_analysis import (
    cmc_from_surface_tension_curve,
    cmc_from_conductivity_curve,
    aggregation_number_from_quenching_curve,
    aggregation_number_from_sls_debye_plot,
    aggregation_number_from_dls,
    aggregation_number_from_svedberg_equation,
)

__version__ = "0.3.0"

__all__ = [
    "clint_ideal_cmc",
    "solve_rubingh_x",
    "rubingh_beta",
    "rubingh_beta_regression",
    "activity_coefficients",
    "asymmetric_margules_activity_coefficients",
    "eommm_global_fit",
    "excess_free_energy",
    "solve_rosen_monolayer_x",
    "rosen_beta_sigma",
    "corrin_harkins_predict_cmc",
    "motomura_ideal_composition",
    "rodenas_x1",
    "rodenas_x1_series",
    "rodenas_activity_coefficients",
    "maeda_free_energy_of_micellization",
    "gibbs_gamma_max",
    "gibbs_a_min",
    "szyszkowski_surface_tension",
    "szyszkowski_fit_K",
    "frumkin_theta",
    "frumkin_surface_tension",
    "hlb_griffin",
    "hlb_davies",
    "guo_effective_eo_chain_length",
    "guo_effective_alkyl_chain_length",
    "guo_effective_po_chain_length",
    "hlb_davies_guo_ecl",
    "hld_ionic",
    "hld_nonionic",
    "cc_mixing_rule",
    "optimal_salinity_ionic",
    "hlb_from_cc_cationic_quat",
    "fit_k_and_cc_from_salinity_scan",
    "tanford_tail_volume",
    "tanford_critical_length",
    "critical_packing_parameter",
    "classify_aggregate_morphology",
    "aggregation_number_spherical",
    "nagarajan_debye_huckel_kappa_inverse",
    "nagarajan_equilibrium_area_ionic",
    "ionic_strength",
    "debye_length",
    "henry_function",
    "zeta_potential_henry",
    "electrophoretic_mobility_relaxation_corrected",
    "zeta_potential_relaxation_corrected",
    "grahame_equation_surface_potential",
    "hydrodynamic_radius_stokes_einstein",
    "perrin_friction_factor",
    "hydrodynamic_radius_perrin_corrected",
    "cmc_to_mole_fraction",
    "counterion_binding_degree",
    "gibbs_free_energy_micellization",
    "mass_action_free_energy_of_micellization",
    "vant_hoff_enthalpy",
    "vant_hoff_multi_point_fit",
    "entropy_micellization",
    "work_of_adhesion",
    "spreading_coefficient",
    "capillary_number",
    "owens_wendt_solid_surface_energy",
    "van_oss_chaudhury_good_solid_surface_energy",
    "molar_solubilization_ratio",
    "micelle_water_partition_coefficient",
    "cmc_from_surface_tension_curve",
    "cmc_from_conductivity_curve",
    "aggregation_number_from_quenching_curve",
    "aggregation_number_from_sls_debye_plot",
    "aggregation_number_from_dls",
    "aggregation_number_from_svedberg_equation",
]
